[package]
name = "almagro"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23.2"
home = "0.5.3"
jfs = "0.7.1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
tui = "0.19"
tui-input = "0.4.2"
